### ISSUE TITLE
New google maps release error

### ISSUE THREAD

**Issue by jeremlb** [marmat/google-maps-api-addons#32] opened 2016-04-26 08:29 UTC

**Comment by jeremlb** [comment] 2016-04-26 08:31
Hi, I use your panomarker library and it's awsome :) With the new release of Google Maps API 3.23 their are an issue, you can't get anymore the panorama DOM div by using panorama.getContext(). If you can fix this, it could be nice. Thanks.

**Comment by marmat** [comment] 2016-05-16 18:03
I don't seem to be able to reproduce your issue. It sounds similar to what was fixed in pull request #28. Did you get the latest version of the library?

**Comment by fflasche** [comment] 2016-06-03 20:37
I have the Same Bug. In your Exemple ist the Bug,too.
http://marmat.github.io/google-maps-api-addons/panomarker/examples/basic.html

Can you fix it, pleas.. 

Thx

**Comment by SaulBurgos** [comment] 2016-06-04 04:53
All examples have the error because are using an old version but the last version on github the bug was fixed . I have checked the code and I saw that the  dom element now is passed like option

**Comment by fflasche** [comment] 2016-06-04 05:30
Okay Thx.
I will Check it, too

**Comment by marmat** [comment] 2016-06-19 16:30
Pulled in the recent changes to the `gh-pages` branch s.t. the examples have the fix as well.

**Closed by marmat** 2016-06-19 16:30 UTC
